title: "Revscoll Store"
email: "r3vscollection@gmail.com"
description: "Grosir & Eceran Sepatu Terpercaya di Tangerang"
baseurl: "https://revscoll.my.id"
url: "https://revscoll.my.id"

# Tema Jekyll 
# theme: minima

markdown: kramdown
